:jbake-menu: -
include::_config.adoc[]
[[gradle-plugin-concept]]
=== Gradle Plugin Concept and Development

:filename: arc42/chapters/chap-08-gradle-plugin.adoc
include::../_feedback.adoc[]

You should definitely read the original https://gradle.org/docs/current/userguide/userguide.html[Gradle User Guide] on custom plugin development.

To enable the <<requirements, required Gradle integration>>,
we implement a lean wrapper as described in the Gradle user guide.



[source, groovy]
class HtmlSanityCheckPlugin implements Plugin<Project> {
    void apply(Project project) {
	project.task('htmlSanityCheck',
		type: HtmlSanityCheckTask,
		group: 'Check')
    }
}


==== Directory Structure and Required Files

----
|-htmlSanityCheck
   |  |-src
   |  |  |-main
   |  |  |  |-org
   |  |  |  |  |-aim42
   |  |  |  |  |  |-htmlsanitycheck
   |  |  |  |  |  |  | ...
   |  |  |  |  |  |  |-HtmlSanityCheckPlugin.groovy // <1>
   |  |  |  |  |  |  |-HtmlSanityCheckTask.groovy
   |  |  |  |-resources
   |  |  |  |  |-META-INF                          // <2>
   |  |  |  |  |  |-gradle-plugins
   |  |  |  |  |  |  |-htmlSanityCheck.properties  // <3>
   |  |  |-test
   |  |  |  |-org
   |  |  |  |  |-aim42
   |  |  |  |  |  |-htmlsanitycheck
   |  |  |  |  |  |  | ...
   |  |  |  |  |  |  |-HtmlSanityCheckPluginTest
   |
----

<1> the actual plugin code: `HtmlSanityCheckPlugin.groovy` and
`HtmlSanityCheckTask.groovy` groovy files
<2> Gradle expects plugin properties in `META-INF`
<3> property file containing the name of the actual implementation class:
`implementation-class=org.aim42.htmlsanitycheck.HtmlSanityCheckPlugin`

==== Passing Parameters From Buildfile to Plugin
To be done

==== Building the Plugin
The plugin code itself is built with gradle.


==== Uploading to Public Archives


==== Further Information on Creating Gradle Plugins
Although writing plugins is described in the Gradle user guide, 
a clearly explained sample is given in a 
https://code4reference.com/2012/08/gradle-custom-plugin-part-2/[Code4Reference] tutorial.
