= HSC CLI Module
:doctype: book
include::../src/docs/asciidoctor-config.ad[]

ifdef::env-github[]
:imagesdir: ../src/docs/images
endif::env-github[]
ifndef::xrefToManual[:xrefToManual: ../README.adoc]
:gradleProperties: link:../gradle.properties[]
ifdef::jbake-type[:gradleProperties: {project-url}/blob/develop/gradle.properties[]]

ifdef::env-github[]
TIP: Use the https://hsc.aim42.org/manual/20_cli.html[HSC Site] for a nicely rendered version of this manual.
endif::env-github[]

The Command Line Interface (CLI) module of HTML Sanity Check (xref:{xrefToManual}[HSC]) enables to check generated or native HTML documentation from the command line.

== Installation (Command Line Interface)

You can run HSC on your machine

* As a <<sec:java-usage,Java application>>{nbsp}->{nbsp}<<sec:java-installation>>, or
* As a <<sec:container-usage,Container>>{nbsp}->{nbsp}<<sec:container-installation>>, or


[[sec:java-installation]]
=== Java Installation

==== Prerequisites

The HSC CLI needs Java 8 (`java` executable) or higher on the respective OS search path (`+${PATH}+` on Linux/macOS, `%path%` on Windows).

==== SDKMAN

If you use https://sdkman.io[SDKMAN], you can install HSC as SDKMAN candidate: `sdk install hsc`.

==== Download

Alternatively, you can download and unpack the CLI release:

* Download the HSC CLI from the https://github.com/aim42/htmlSanityCheck/releases[release{nbsp}page].
* Unpack the file in a convenient place, e.g., `/usr/local/hsc`.
* Add the unpacked bin directory to your path, e.g. (for Unix), `+PATH=${PATH}:/usr/local/hsc/bin+`.

[[sec:container-installation]]
=== Container (Docker) Installation

Alternatively, you can use a local Container runtime (such as https://www.docker.com/[Docker] or https://podman.io/[Podman]) and execute HSC as a container.
In this case, no preliminary installation is necessary (except for the container runtime) you can directly <<sec:container-usage,run HSC>>.

[NOTE]
====
While HSC supports both Docker and Podman as container runtimes, our examples and automated tests currently only use Docker.
The commands should work similarly with Podman by replacing `docker` with `podman` in the examples.
====

== Usage

[[sec:java-usage]]
=== Java usage

Execute the CLI tool with the following command.
If the `sourceDirectory` is omitted, HSC uses the current directory as base-directory to search for HTML files.

Linux / macOS::
+
[source,sh]
----
hsc [ options ] [ sourceDirectory ]
----

Windows::
+
[source,powershell]
----
hsc.bat [ options ] [ sourceDirectory ]
----

[[sec:container-usage]]
=== Using the Container image

You can run HSC without installing Java or the CLI by using the Container image published at the GitHub Container Registry:
`ghcr.io/aim42/hsc`.

Unix (shell) example (Linux/macOS)::
+
[source,sh]
----
# Assume your HTML files are under ./docs and you want the report under ./build/reports
docs_dir="${PWD}/docs"
reports_dir="${PWD}/build/reports"
mkdir -p "$reports_dir"

# Run the Docker image, mount the docs and a host reports directory, and set the working directory
docker run --rm \
  -v "${docs_dir}:${docs_dir}" \
  -v "${reports_dir}:/reports" \
  -w "${docs_dir}" \
  ghcr.io/aim42/hsc:latest \
  -r /reports
----

Add options as necessary (example)::
+
[source,sh]
----
# Exclude some external links via regex and restrict checked suffixes
docker run --rm \
  -v "$docs_dir:$docs_dir" \
  -v "$reports_dir:/reports" \
  -w "$docs_dir" \
  ghcr.io/aim42/hsc:latest \
  -r /reports \
  --exclude https://www.example.com/.* \
  --suffix html,htm
----

Windows PowerShell example::
+
[source,powershell]
----
$DocsDir = (Resolve-Path ./docs).Path
$ReportsDir = (Resolve-Path ./build/reports).Path
New-Item -Force -ItemType Directory $ReportsDir | Out-Null

docker run --rm `
  -v "$DocsDir`:$DocsDir" `
  -v "$ReportsDir`:/reports" `
  -w "$DocsDir" `
  ghcr.io/aim42/hsc:latest `
  -r /reports
----

Notes::

* The container entrypoint simply invokes the CLI (`java -jar /hsc.jar`) and forwards all arguments, so you can pass the same options as described below.
* Reports will be written to the directory you mount at `/reports` when using `-r /reports`.
* Tags: use `:latest` for the latest released image.
Development builds may also be available using branch-name tags (used in integration tests).
* The integration test `integration-test/build.gradle` contains a full working example of the Docker invocation used in CI.

=== Options

The CLI tool exposes a few options as part of its configuration:

[horizontal]
<sourceDirectory> (optional):: HSC searches this directory for HTML files.
+
Type: Directory
+
Default: Current directory (`.`)

`--sourceDocuments` <...> (optional):: An override to process several source files, which must be a subset of all files available in `sourceDir`.
+
Type: List of files
+
Default: All files in `sourceDir` whose names end with `.html`

`--checkingResultsDir` <...> (optional):: Directory where HSC writes the checking results.
+
Type: Directory
+
Default: `./reports/htmlSanityCheck/`

`--junitResultsDir` <...> (optional):: Directory where HSC writes the results in JUnit XML format.
Many tools can read JUnit XML, including CI environments.
+
Type: Directory
+
Default: `./test-results/htmlchecks/`

`--failOnErrors` (optional):: Fail the build if HSC detected any error in the checked pages.
+
Type: Boolean
+
Default: `false`

`--httpConnectionTimeout` <value> (optional):: Timeout for HTTP requests in milliseconds.
+
Type: Integer
+
Default: `5000`

`--ignoreLocalHost` (optional):: Ignore localhost as the hostname.
+
Type: Boolean
+
Default: `false`

`--ignoreIPAddresses` (optional):: Ignore IP addresses as hostname.
+
Type: Boolean
+
Default: `false`

`--checkerClasses` <...> (optional):: The set of checker classes to be executed.
+
Type: List
+
Default:
+
[source,groovy]
.Checker Classes
----
include::../htmlSanityCheck-core/src/main/java/org/aim42/htmlsanitycheck/check/AllCheckers.java[tag=checker-classes,indent=0]
----

`--excludes` (optional):: This is a set of regular expressions of URLs or even hosts that HSC should not check.
+
Type: Set.
+
Default: Empty list
+
[source,groovy]
----
[]
----

`--httpWarningCodes` (optional):: HTTP response codes are treated as warning.
+
Type: List
+
Default:
+
[source,groovy]
----
include::../htmlSanityCheck-core/src/main/java/org/aim42/htmlsanitycheck/tools/Web.java[tag=HTTP_WARNING_CODES,indent=0]
// Redirects included
include::../htmlSanityCheck-core/src/main/java/org/aim42/htmlsanitycheck/tools/Web.java[tag=HTTP_REDIRECT_CODES,indent=0]
----
+
[NOTE]
.HTTP Redirects
====
Note that HSC treats HTTP redirects as a warning to make the user aware of the correct
or new location (cf.{nbsp}{project-issues}/244[Issue 244]).
Some HSC reports contain the respective location.
====

`--httpErrorCodes` (optional):: HTTP response codes which are treated as errors.
+
Type: List
+
Default:
+
[source,groovy]
----
include::../htmlSanityCheck-core/src/main/java/org/aim42/htmlsanitycheck/tools/Web.java[tag=HTTP_ERROR_CODES,indent=0]
----

`--httpSuccessCodes` (optional):: HTTP response codes that HSC treats as success.
+
Type: List
+
Default:
+
[source,groovy]
----
include::../htmlSanityCheck-core/src/main/java/org/aim42/htmlsanitycheck/tools/Web.java[tag=HTTP_SUCCESS_CODES,indent=0]
----

[[sidebar:http-response-codes]]
.HTTP response code handling
****
The lists shown above are the default HTTP response codes handled by HSC.
The mentioned configurations effectively move the configured codes around, i.e., if you add `308` to `httpErrorCodes` it is automatically removed from its default list (`httpWarningCodes`).
****

== Examples

=== Basic Example

[source,sh]
----
java -jar htmlSanityCheck-cli-<version>.jar --sourceDir ./docs
----

=== Extended Example

[source,sh]
----
java -jar htmlSanityCheck-cli-<version>.jar \
  --sourceDir ./docs \
  --checkingResultsDir ./report/htmlchecks \
  --failOnErrors true \
  --httpConnectionTimeout 1000 \
  --checkerClasses DuplicateIdChecker,MissingImageFilesChecker
----

== Compatibility

We test the HSC CLI tool with the following Java versions:

* Java 8
* Java 11
* Java 17
* Java 21

== Development Versions

In case you want to use a current development (or arbitrary branch or tag) version from GitHub, you can build the CLI tool from source.

Clone the repository::
+
[source,sh]
----
git clone https://github.com/aim42/htmlSanityCheck.git
cd htmlSanityCheck
----

Build the CLI tool::
+
[source,sh]
----
./gradlew integrationTest
----
+
Gradle generates the application to `htmlSanityCheck-cli/build/install/hsc/`.
