
== Technical and Crosscutting Concepts

include::chap-08-checking-domain.adoc[]
include::chap-08-gradle-plugin.adoc[]

include::chap-08-checking-algorithms.adoc[]
include::chap-08-html-encapsulation.adoc[]



[[reporting-concept]]
=== Flexible Reporting
kbd:[HtmlSC] allows for different output formats:

* formats (HTML and text) and
* destinations (file and console)


The reporting subsystem uses the template method pattern to allow different output formats
(e.g. Console and HTML). The overall structure of reports is always the same:

Graphical clients can use the API of the reporting subsystem to display
reports in arbitrary formats.

The (generic and abstract) reporting is implemented in the abstract Reporter class
as follows:

[source, groovy]
 /**
     * main entry point for reporting - to be called when a report is requested
     *
     * Uses template-method to delegate most concrete implementations to subclasses
     */
    public void reportFindings() {
        initReport()            // <1>
        reportOverallSummary()  // <2>
        reportAllPages()        // <3>
        closeReport()           // <4>
    }
    private void reportAllPages() {
        pageResults.each { pageResult ->
            reportPageSummary( pageResult ) // <5>
            pageResult.singleCheckResults.each { resultForOneCheck ->
               reportSingleCheckSummary( resultForOneCheck )  // <6>
               reportSingleCheckDetails( resultForOneCheck )  // <7>  
               reportPageFooter()                             // <8>
        }
    }


[WARNING]
This section needs to be written.


=== Styling the Reporting Output

* The HtmlReporter explicitly generates css classes together with the html elements,
based upon css styling re-used from the Gradle JUnit plugin.
* Stylesheets, a minimized version of JQuery javascript library plus some icons
are copied at report-generation time from the jar-file to the report output directory.


==== Attributions
Credits for the arrow-icon https://www.iconfinder.com/icons/118743/arrow_up_icon


