:filename: development/publishing.adoc
:jbake-title: Publishing HSC Releases
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: development
:jbake-order: 80
== {jbake-title}
:icons: font
:toc:
:toclevels: 3
:toc-position: right
:experimental:
:markdown-suffix: md
ifdef::backend-html5[:markdown-suffix: html]

HSC (Core and Gradle plugin) can be published to https://central.sonatype.com/search?q=org.aim42.htmlSanityCheck[Maven Central] (MC) for retrieval by its consumers.

Traditional retrieval as Gradle plugin from https://plugins.gradle.org[Gradle Plugin Portal] is still possible,
as they are redirecting plugin downloads automatically to Maven Central.

WARNING: Only note that newer versions (>= 2.0.0) currently do not show up in the https://plugins.gradle.org/search?term=org.aim42.htmlSanityCheck[web interface].

== Prerequisites

[[sec:maven-central-account]]
=== Maven Central (Sonatype) account

Make yourself familiar with https://central.sonatype.org/publish-ea/publish-ea-guide/[the publishing process].

[CAUTION]
.Maven Central credentials needed
====
You need respective credentials to upload files to Maven Central for the `org.aim42.htmlSanityCheck` namespace.
Talk to Gernot Starke to get these permissions.
====

You will need to https://central.sonatype.org/register/central-portal/#create-an-account[sign up for Maven Central]
(or, to be more precise, to its provider, Sonatype).
Additionally,
you need
to create https://central.sonatype.org/publish/generate-portal-token/[a portal token]footnote:[This is a different user/password than your login user.].

Check out <<sec:release-environment>> how to inject these credentials in your environment for publication activities.

[[sec:prerequisits-gpp]]
=== Gradle Plugin Portal

It is possible to publish new versions of the Plugin to the https://plugins.gradle.org/[Gradle Plugin Portal] (GPP).

[[caution:gpp-publisher]]
[CAUTION]
.Unique publisher required
====
Only one person at a time can take responsibility for publishing of plugins (Or new versions) to GPP.
Currently, this is https://plugins.gradle.org/u/GerdAschemann[Gerd Aschemann] (following https://plugins.gradle.org/u/gernotstarke[Gernot Starke]).
Only the current maintainer can change the ownership (by creating a new ownership transformation request at https://github.com/gradle/plugin-portal-requests[]).
====

After creating a user, you need to `login` to GPP:

[source,shell]
----
:htmlSanityCheck-gradle-plugin
----

This will put the respective key and secret to your `~/.gradle/gradle.properties` file.
Alternatively, you can set these as environment variables:

[source,shell]
----
export GRADLE_PUBLISH_KEY=...
export GRADLE_PUBLISH_SECRET=...
----

[[sec:artifact-signing]]
=== Artifact signing

To successfully upload artifacts and other files (POM etc.), a valid PGP signature is required.
A proper GPG (agent) setup is beyond the scope of this tutorial.
Therefore, you need to set up GnuPG in your local `+${HOME}/.gradle/gradle.properties+`,
according to the https://docs.gradle.org/current/userguide/signing_plugin.html#sec:signatory_credentials[Gradle Signatory documentation].

Add the following entries:

[source,properties]
----
signing.keyId=24875D73 <1>
signing.secretKeyRingFile=/Users/me/.gnupg/secring.gpg <2>
signing.password=<SECRET> # <3>
----
<1> You have to provide the id of your key (of course).
<2> Note that you need to specify the literal path to your home directory; it is not possible to refer to system properties like `+${user.home}+` here.
<3> Instead of putting the clear text password into the file, you should  provide it on the command line when calling Gradle
+
[source,shell]
----
./gradlew -Psigning.password=... <task>
----

[[tip:gpg-agent]]
[TIP]
.Use GPG Agent
====
Alternatively,
you may use the https://www.gnupg.org/documentation/manuals/gnupg24/gpg-agent.1.html[GPG Agent] of your https://gnupg.org/[GnuPG] installation
to cache the secret in memory,
thereby reducing the risk of accidentally exposing the clear text passphrase in your command line or environment.

You can make use of it by setting the flag `useGpgCmd` to `true`:

[source,shell]
----
./gradlew -PuseGpgCmd=true <task>
----

Note that the (native) `gpg` command is used in background and that it cannot request the passphrase when executed.
This may lead to errors like

[source]
----
gpg: Sorry, we are in batchmode - can't get input

FAILURE: Build failed with an exception.
----

In this case, you have to make sure the agent is started and the password is cached, e.g., by executing

[source,shell]
----
echo empty | gpg --clearsign -o /dev/null
----
====

[[sec:release-environment]]
=== JReleaser Credentials / Environment Settings

You will have to set the following environment variable to perform misc. https://jreleaser.org[JReleaser] actions.

[source,shell]
----
export JRELEASER_MAVENCENTRAL_STAGE=UPLOAD # <1>
export JRELEASER_GITHUB_TOKEN=... # <2>
export JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_USERNAME=... # <3>
export JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_PASSWORD=... # <3>
export JRELEASER_ANNOUNCE_MASTODON_ACCESS_TOKEN=... <4>
----
<1> Maven Central publications require two steps.
This variable setting enables <<sec:stage-to-maven-central,
upload to the staging area>>, perform <<sec:publish-to-maven-central,the final publication>> interactively.
<2> Get an appropriate GitHub token (needs write access to the repository).
<3> Follow the <<sec:maven-central-account,steps above>> to get the required Maven credentials.
Create a deployment user and password in your Maven Central (Sonatype) https://central.sonatype.com/account[account].
<4> Access token for your Mastodon Account (on https://mastodon.social[]footnote:[Publishing to a different Mastodon server requires more changes.]).


== Publishing actions

=== Adjust version number

Set the version number in xref:gradle.properties[../../../gradle.properties] to the next value.

=== Maintain ChangeLog

Add the respective changes to xref:CHANGELOG.{markdown-suffix}[../../../CHANGELOG.md]

=== Build / Test

Clean, check (test), and perform integration tests:

[source,shell]
----
./gradlew clean check integrationTest
----

[[sec:stage-to-maven-central]]
=== Sign / Upload to Maven Central

Sign artifacts and load them up to Maven Central via https://jreleaser.org[JReleaser].

[source,shell]
----
./gradlew jreleaserRelease -PenableSigning=true -Psigning.password=... # <1> <2>
----
<1> Checkout <<sec:artifact-signing>> for more information.
<2> The `enableSigning` flag is necessary to enforce signing (which is not necessary for local installations,
integration testing, etc.)

+
The `jreleaserRelease` task will

* Implicitly call the task `signAll` which signs
and pushes all required files for publication to a local repository.
* Then pick them up from there and load them up to the Maven Central staging area as a new version.
* https://github.com/aim42/htmlSanityCheck/releases[Release current state to GitHub] and tag the current version accordingly.

[TIP]
.Use GPG Agent (command) in practice
====
If you have GPG configured properly, you may use the <<tip:gpg-agent,GPG-Agent>>.

[source,bash,subs="callouts+"]
----
./gradlew jreleaserDeploy -PenableSigning=true -PuseGpgCmd=true
----
====

=== Publish on Gradle Plugin Portal

Set the respective credentials (cf. <<sec:prerequisits-gpp,GPP Prerequisites>>).
Then publish on GPP:

[source,shell]
----
./gradlew -Pprofile=gpp :htmlSanityCheck-gradle-plugin:publishPlugins # <1>
----
<1> An additional `--validate-only` allows to check credentials

Performing this for the first time after a <<caution:gpp-publisher,Change of the maintainer>> may take some time as the Gradle team will perform some checks.

[TIP]
====
You can delete the published version if you fail with one of the other steps.
====

[[sec:publish-to-maven-central]]
=== Publish on Maven Central

Publish the staged version on Maven Central,
i.e., https://central.sonatype.com/publishing[Sonatype Central].

=== Announce new release on Social Media

Finally, announce the new release on Social Media, i.e., https://mastodon.social/deck/tags/HTMLSanityCheck[Mastodon (Social)].

[source,bash]
----
./gradlew jreleaserAnnounce
----
