:filename: development/publishing.adoc
:jbake-title: Publishing HSC Releases
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: development
:jbake-order: 80
== {jbake-title}
:icons: font
:toc:
:toclevels: 3
:toc-position: right
:experimental:
:markdown-suffix: md
ifdef::backend-html5[:markdown-suffix: html]

HSC (Core and Gradle plugin) can be published to https://central.sonatype.com/search?q=org.aim42.htmlSanityCheck[Maven Central] (MC) for retrieval by its consumers.

Traditional retrieval as Gradle plugin from https://plugins.gradle.org[Gradle Plugin Portal] is still possible,
as they are redirecting plugin downloads automatically to Maven Central.

WARNING: Only note that newer versions (>= 2.0.0) currently do not show up in the https://plugins.gradle.org/search?term=org.aim42.htmlSanityCheck[web interface].

== Prerequisites

=== Maven Central (Sonatype) account

Make yourself familiar with https://central.sonatype.org/publish-ea/publish-ea-guide/[the publishing process].

[CAUTION]
.Credentials needed
====
You need respective credentials to upload files to Maven Central for the `org.aim42.htmlSanityCheck` namespace.
Talk to Gernot Starke to get these permissions.
====

You will need to https://central.sonatype.org/register/central-portal/#create-an-account[sign up for Maven Central]
(or, to be more precise, to its provider, Sonatype).
Additionally, you need to create https://central.sonatype.org/publish/generate-portal-token/[a portal token].

[[sec:artifact-signing]]
=== Artifact signing

To successfully upload artifacts and other files (POM etc.), a valid PGP signature is required.
A proper GPG (agent) setup is beyond the scope of this tutorial.
Therefore, you need to set up GnuPG in your local `+${HOME}/.gradle/gradle.properties+`,
according to the https://docs.gradle.org/current/userguide/signing_plugin.html#sec:signatory_credentials[Gradle Signatory documentation].

Add the following entries:

[source,properties]
----
signing.keyId=24875D73 <1>
signing.secretKeyRingFile=/Users/me/.gnupg/secring.gpg <2>
signing.password=<SECRET> # <3>
----
<1> You have to provide the id of your key (of course).
<2> Note that you need to specify the literal path to your home directory; it is not possible to refer to system properties like `+${user.home}+` here.
<3> Instead of putting the clear text password into the file, you should  provide it on the command line when calling Gradle
+
[source,shell]
----
./gradlew -Psigning.password=... <task>
----

[[tip:gpg-agent]]
[TIP]
.Use GPG Agent
====
Alternatively,
you may use the https://www.gnupg.org/documentation/manuals/gnupg24/gpg-agent.1.html[GPG Agent] of your https://gnupg.org/[GnuPG] installation
to cache the secret in memory,
thereby reducing the risk of accidentally exposing the clear text passphrase in your command line or environment.

You can make use of it by setting the flag `useGpgCmd` to `true`:

[source,shell]
----
./gradlew -PuseGpgCmd=true <task>
----

Note that the (native) `gpg` command is used in background and that it cannot request the passphrase when executed.
This may lead to errors like

[source]
----
gpg: Sorry, we are in batchmode - can't get input

FAILURE: Build failed with an exception.
----

In this case, you have to make sure the agent is started and the password is cached, e.g., by executing

[source,shell]
----
echo empty | gpg --clearsign -o /dev/null
----
====

== Publishing actions

Adjust version number::
Set the version number in xref:gradle.properties[../../../gradle.properties] to the next value.

Maintain ChangeLog::
Add the respective changes to xref:CHANGELOG.{markdown-suffix}[../../../CHANGELOG.md]

Build / Test::
Clean, check (test), and perform integration tests:
+
[source,bash,subs="callouts+"]
----
./gradlew clean check integrationTest
----

Sign / Upload to Maven Central::
Sign artifacts and load them up to Maven Central via https://jreleaser.org[JReleaser].
+
[source,bash,subs="callouts+"]
----
./gradlew jreleaserRelease -PenableSigning=true -Psigning.password=... # <1> <2>
----
<1> Checkout <<sec:artifact-signing>> for more information.
<2> The `enableSigning` flag is necessary to enforce signing (which is not necessary for local installations,
integration testing, etc.)

+
The `jreleaserRelease` task will

* Implicitly call the task `signAll` which signs
and pushes all required files for publication to a local repository.
* Then pick them up from there and load them up to the Maven Central staging area as a new version.
* https://github.com/aim42/htmlSanityCheck/releases[Release current state to GitHub] and tag the current version accordingly.

[TIP]
.Use GPG Agent (command) in practice
====
If you have GPG configured properly, you may use the <<tip:gpg-agent,GPG-Agent>>.

[source,bash,subs="callouts+"]
----
./gradlew jreleaserDeploy -PenableSigning=true -PuseGpgCmd=true
----
====

Publish on Maven Central::
Finally, publish the staged version on Maven Central,
i.e., https://central.sonatype.com/publishing[Sonatype Central].
