:filename: development/publishing.adoc
=== Publishing kbd:htmlSC Releases

==== Background

Our Gradle build stores all artifacts and their meta-data (POM + module files,
as well as their respective hashes and signatures) in a local Maven repository.
They are subject to integration tests.
Finally, they can be uploaded to Maven Central (as ZIP file).

[[item:local-repository]]
* The build stores these files to the root build directory.
+
[source,groovy]
.Local Maven repository for integration testing and publication
----
include::../../../build.gradle[tag=mavenBuildRepo]
----

[[item:zip-file]]
* And it stores the ZIP file there as well
+
[source,groovy]
.Generated ZIP file for publication
----
include::../../../build.gradle[tag=artifactsZip]
----

[IMPORTANT]
.Setup GnuPG signing
====
To successfully sign the artifacts
you need to set up GnuPG in your local `+${HOME}/.gradle/gradle.properties+`,
according to the https://docs.gradle.org/current/userguide/signing_plugin.html#sec:signatory_credentials[Gradle Signatory documentation].

Add the following entries:

[source,properties]
----
signing.keyId=24875D73
signing.password=secret # <1>
signing.secretKeyRingFile=/Users/me/.gnupg/secring.gpg <2>
----
<1> Instead of provisioning the clear text password, you could also provide it on the command line when calling Gradle:
+
[source,shell]
----
./gradlew -Psigning.password=... <task>
----
<2> Note that you need to specify the literal path to your home directory; it is not possible to refer to system properties like `+${user.home}+` here.
====

==== Publishing actions

Adjust version number::
Set the version number in xref:../../../gradle.properties[] to the next value.

Build / publish local / sign::
Generate artifacts and publish them to the local Maven repository for integration tests
+
[source,bash,subs="callouts+"]
----
./gradlew clean integrationTest zipArtifacts # <1> <2>
----
<1> The `integrationTest` task will implicitly call the task `publishAllPublicationsToMyLocalRepositoryForFullIntegrationTestsRepository` which pushes all required files for publication to the <<item:local-repository,repository>>.
<2> The `zipArtifacts` task will generate the <<item:zip-file,ZIP file>> for publication.

Upload ZIP to Maven Central::
Finally, upload the resulting ZIP file (manually) to Maven Central,
i.e., https://central.sonatype.com/publishing[Sonatype Central].
+
[CAUTION]
.Credentials needed
====
You need respective credentials to upload files to Maven Central for the `org.aim42.htmlSanityCheck` namespace.
Talk to Gernot Starke to get these permissions.
====
