:filename: development/publishing.adoc
=== Publishing kbd:htmlSC Releases

kbd:htmlSC (Core and Gradle plugin) can be published to https://central.sonatype.com/search?q=org.aim42.htmlSanityCheck[Maven Central] (MC) for retrieval by its consumers.

Traditional retrieval as Gradle plugin from https://plugins.gradle.org[Gradle Plugin Portal] is still possible,
as they are redirecting plugin downloads automatically to Maven Central.

WARNING: Only note that newer versions (>= 2.0.0) currently do not show up in the https://plugins.gradle.org/search?term=org.aim42.htmlSanityCheck[web interface].

==== Prerequisites

===== Maven Central (Sonatype) account

Make yourself familiar with https://central.sonatype.org/publish-ea/publish-ea-guide/[the publishing process].

[CAUTION]
.Credentials needed
====
You need respective credentials to upload files to Maven Central for the `org.aim42.htmlSanityCheck` namespace.
Talk to Gernot Starke to get these permissions.
====

You will need to https://central.sonatype.org/register/central-portal/#create-an-account[sign up for Maven Central]
(or, to be more precise, to its provider, Sonatype).
Additionally, you need to create https://central.sonatype.org/publish/generate-portal-token/[a portal token].

[[sec:artifact-signing]]
===== Artifact signing

To successfully upload artifacts and other files (POM etc.), a valid PGP signature is required.
Therefore, you need to set up GnuPG in your local `+${HOME}/.gradle/gradle.properties+`,
according to the https://docs.gradle.org/current/userguide/signing_plugin.html#sec:signatory_credentials[Gradle Signatory documentation].

Add the following entries:

[source,properties]
----
signing.keyId=24875D73
signing.secretKeyRingFile=/Users/me/.gnupg/secring.gpg <1>
signing.password=<SECRET> # <2>
----
<1> Note that you need to specify the literal path to your home directory; it is not possible to refer to system properties like `+${user.home}+` here.
<2> Instead of putting the clear text password into the file, you should  provide it on the command line when calling Gradle
+
[source,shell]
----
./gradlew -Psigning.password=... <task>
----

==== Publishing actions

Adjust version number::
Set the version number in xref:../../../gradle.properties[] to the next value.

Build / Test::
Clean, check (test), and perform integration tests:
+
[source,bash,subs="callouts+"]
----
./gradlew clean check integrationTest
----

Sign / Upload to Maven Central::
Sign artifacts and load them up to Maven Central via https://jreleaser.org[JReleaser].
+
[source,bash,subs="callouts+"]
----
./gradlew jreleaserDeploy -PenableSigning=true -Psigning.password=... # <1> <2>
----
<1> Checkout <<sec:artifact-signing>> for more information.
<2> The `enableSigning` flag is necessary to enforce signing (which is not necessary for local installations,
integration testing, etc.)

The `jreleaserDeploy` task will implicitly call the task `signAll` which signs
and pushes all required files for publication to a local repository.
JReleaser picks them up from there and loads them up to the Maven Central staging area as a new version.

Publish on Maven Central::
Finally, publish the staged version on Maven Central,
i.e., https://central.sonatype.com/publishing[Sonatype Central].
