:filename: development/publishing.adoc
=== Publishing kbd:htmlSC Releases

==== Background

Our Gradle build stores all artifacts and their meta-data (POM + module files,
as well as their respective hashes and signatures) in a local Maven repository.
They are subject to integration tests.
Finally, they can be uploaded to Maven Central (as ZIP file).

* The build stores these files to the root build directory.
+
[source, groovy]
----
include::../../../build.gradle[tag=mavenBuildRepo]
----

* And it stores the ZIP file there as well
+
[source, groovy]
----
include::../../../build.gradle[tag=artifactsZip]
----

==== Publishing actions

Adjust version number::
Set the version number in xref:../../../gradle.properties[] to the next value.

Build / publish local::
Generate artifacts and publish them to the local Maven repository for integration tests
+
[source,bash,subs="callouts+"]
----
./gradlew clean integrationTests # <1>
----
<1> This will implicitly call the task `publishAllPublicationsToMyLocalRepositoryForFullIntegrationTestsRepository` which pushes all required files for publication to the repository.

Sign::
Sign artifacts, POMs, and modules with GPG.
+
[source,bash]
----
for i in $(find build -name "*.jar" -o -name "*.pom" -o -name "*.module"); do \
  gpg --yes -ab ${i}; \
done
----

+
[NOTE]
.Setup PGP / GnuPG
====
Setting up PGP (or GnuPG) is out of scope for this document.

Please refer to the respective documentation.
====

Build ZIP::
Create a ZIP-File from all artifacts, POMs, and modules, their hashes, and signatures.
+
[source, bash]
----
./gradlew zipArtifacts
----

Upload ZIP to Maven Central::
Finally, upload the resulting ZIP file (manually) to Maven Central,
i.e., https://central.sonatype.com/publishing[Sonatype Central].
+
[CAUTION]
.Credentials needed
====
You need respective credentials to upload files to Maven Central for the `org.aim42.htmlSanityCheck` namespace.
Talk to Gernot Starke to get these permissions.
====
