= HSC Maven Plugin
:doctype: book
include::../src/docs/asciidoctor-config.ad[]

image:https://img.shields.io/maven-central/v/org.aim42.htmlsanitycheck/htmlsanitycheck-maven-plugin[link=https://central.sonatype.com/artifact/org.aim42.htmlsanitycheck/htmlsanitycheck-maven-plugin]

ifdef::env-github[]
:imagesdir: ../src/docs/images
endif::env-github[]
ifndef::xrefToManual[:xrefToManual: ../README.adoc]
:mavenProperties: link:../maven.properties[]
ifdef::jbake-type[:mavenProperties: {project-url}/blob/develop/maven.properties[]]

ifdef::env-github[]
TIP: Use the https://hsc.aim42.org/manual/40_maven-plugin.html[HSC Site] for a nicely rendered version of this manual.
endif::env-github[]

The {maven-url}[Maven] plugin of HTML Sanity Check (xref:{xrefToManual}[HSC]) enables to check generated or native HTML documentation from the Maven build.

[IMPORTANT]
.Breaking change since 2.0.0-rc4: lowercase GA coordinates
====
The Maven `groupId` and `artifactId` were lowercased to comply with Maven conventions and to support repositories that enforce this (e.g., GitHub Packages).
See https://github.com/aim42/htmlSanityCheck/issues/432[Issue 432] and the https://github.com/aim42/htmlSanityCheck/blob/main/CHANGELOG.md[CHANGELOG] for the migration table.

Versions up to and including `2.0.0-rc4` remain available under the historical CamelCase coordinates at https://central.sonatype.com/namespace/org.aim42.htmlSanityCheck[Maven Central].
====

[[sec:installation]]
== Installation (Maven Plugin)

=== Default Installation

Use the following snippet inside a Maven build file:

.build.maven
[source,xml,subs="attributes+"]
----
<plugin>
    <groupId>org.aim42.htmlsanitycheck</groupId>
    <artifactId>htmlsanitycheck-maven-plugin</artifactId>
    <version>{hsc-version}</version> // <1>
    <executions>
        <execution>
            <phase>compile</phase>
            <goals>
                <goal>sanity-check</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <sourceDocuments>
            <file>src/file-to-test.html</file> <2>
        </sourceDocuments>
        <sourceDir>src</sourceDir> <3>
    </configuration>
</plugin>
----
<1> Checkout <<box:current-version,current version>>
<2> List the files you want to check here.
<3> Directory where the HTML files are located.

[[box:current-version]]
[IMPORTANT]
.Latest (development) versions
====
* The latest https://github.com/aim42/htmlSanityCheck/releases[release version] is defined in https://github.com/aim42/htmlSanityCheck/blob/main/gradle.properties[`gradle.properties` on the `main` branch].
* The current (development) version is defined in {gradleProperties}
+
[source]
.Development version
----
include::../gradle.properties[tag=version]
----
====

[[sec:development-versions]]
=== Development versions

Development snapshots are published to *GitHub Packages* for https://github.com/orgs/aim42/packages?repo_name=htmlSanityCheck[`aim42/htmlSanityCheck`].
GitHub Packages requires authentication even for public packages — supply a Personal Access Token (PAT) with `read:packages` scope via `~/.m2/settings.xml`:

.~/.m2/settings.xml
[source,xml,subs="attributes+"]
----
<settings>
  <servers>
    <server>
      <id>github-aim42</id>
      <username>YOUR_GITHUB_USERNAME</username>
      <password>YOUR_PAT_WITH_read:packages</password>
    </server>
  </servers>
</settings>
----

Then declare the repository in your project's `pom.xml`:

[source,xml,subs="attributes+"]
----
<pluginRepositories>
  <pluginRepository>
    <id>github-aim42</id>
    <url>https://maven.pkg.github.com/aim42/htmlSanityCheck</url>
    <snapshots><enabled>true</enabled></snapshots>
  </pluginRepository>
</pluginRepositories>
----

[WARNING]
.JitPack (deprecated)
====
JitPack support is retained for backwards compatibility but is no longer recommended for the reasons documented in https://github.com/aim42/htmlSanityCheck/issues/432[Issue 432] (missing branches after force-push, stale builds, first-time timeouts).
Prefer GitHub Packages.
====

[[sec:usage]]
== Usage

This task exposes a few properties as part of its configuration:

[horizontal]
`sourceDir` (mandatory):: Directory where the HTML files are located.
+
Type: Directory.

`sourceDocuments` (optional):: An override to process several source files, which may be a subset of all files available in `+{sourceDir}+`.
+
Type: `org.maven.api.file.FileCollection`.
+
Default: All files in `+{sourceDir}+` whose names end with `.html`.

`checkingResultsDir` (optional):: Directory where the checking results are written to.
+
Type: Directory.
+
Default: `+{buildDir}+/reports/htmlSanityCheck/`

`junitResultsDir` (optional):: Directory where the results are written to in JUnit XML format.
JUnit XML can be read by many tools, including CI environments.
+
Type: Directory.
+
Default: `+{buildDir}+/test-results/htmlchecks/`

`failOnErrors` (optional):: Fail the build if any error was found in the checked pages.
+
Type: Boolean.
+
Default: `false`.

`httpConnectionTimeout` (optional):: Timeout for http requests in ms.
+
Type: Integer.
+
Default: `5000`.

`ignoreLocalHost` (optional):: Ignore localhost as the hostname.
+
Type: Boolean.
+
Default: `false`.

`ignoreIPAddresses` (optional):: Ignore IP addresses as hostname.
+
Type: Boolean.
+
Default: `false`.

`checkerClasses` (optional):: The set of checker classes to be executed.
+
Type: List.
+
Default: All available checker classes.
+
[source,groovy]
.Checker Classes
----
include::../htmlSanityCheck-core/src/main/java/org/aim42/htmlsanitycheck/check/AllCheckers.java[tag=checker-classes,indent=0]
----

`excludes` (optional):: This is a set of regular expressions of URLs or even hosts that HSC should not check.
+
Type: Set.
+
Default: Empty list
+
[source,groovy]
----
[]
----

`httpWarningCodes` (optional):: Additional HTTP response codes are treated as warning.
+
Type: List.
+
Default:
+
[source,java]
----
include::../htmlSanityCheck-core/src/main/java/org/aim42/htmlsanitycheck/tools/Web.java[tag=HTTP_WARNING_CODES,indent=0]
// Redirects included
include::../htmlSanityCheck-core/src/main/java/org/aim42/htmlsanitycheck/tools/Web.java[tag=HTTP_REDIRECT_CODES,indent=0]
----
+

[NOTE]
.HTTP Redirects
====
Note that HTTP redirects are treated as a warning to make the user aware of the correct or new location (cf. {project-issues}/244[Issue 244]).
Some HSC reports often contain the respective location.
====

`httpErrorCodes` (optional):: Additional HTTP response codes are treated as errors.
+
Type: List.
+
Default:
+
[source,groovy]
----
include::../htmlSanityCheck-core/src/main/java/org/aim42/htmlsanitycheck/tools/Web.java[tag=HTTP_ERROR_CODES,indent=0]
----

`httpSuccessCodes` (optional):: Additional HTTP response codes are treated as a success.
+
Type: List.
+
Default:
+
[source,java]
----
include::../htmlSanityCheck-core/src/main/java/org/aim42/htmlsanitycheck/tools/Web.java[tag=HTTP_SUCCESS_CODES,indent=0]
----

[[sidebar:http-response-codes]]
.HTTP response code handling
****
The lists shown above are the default HTTP response codes handled by HSC.
The mentioned configurations effectively move the configured codes around, i.e., if you add `308` to `httpErrorCodes` it is automatically removed from its default list (`httpWarningCodes`).
****


[[sec:examples]]
== Examples

=== Small Example
`build.maven`
[source,xml]
----
tbd
----

=== Extended example

.`build.maven`
[source,xml,subs='attributes']
----

tbd

----

== Compatibility

The Plugin is only tested with Maven 3.9.x but should also work with previous versions later than Maven 3.6.x, as well as newer versions (4.x).
