name: Publish Site to GitHub Pages

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      publish_site:
        type: boolean
        description: 'Publish To GH Pages'
        default: false

jobs:
  publish-to-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Deploy Pages
        if: github.event.inputs.publish_site
        id: deployment
        uses: actions/deploy-pages@v4
